apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  labels:
    system: openstack
    service: monitoring
    component: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: grafana
      annotations:
        checksum/grafana.etc: {{ include "grafana/templates/grafana-etc-configmap.yaml" . | sha256sum }}
        checksum/grafana.bin: {{ include "grafana/templates/grafana-bin-configmap.yaml" . | sha256sum }}
        checksum/grafana.ini: {{ include "grafana/templates/_grafana.ini.tpl" . | sha256sum }}
        checksum/ldap.toml: {{ include "grafana/templates/_ldap.toml.tpl" . | sha256sum }}
        checksum/grafana-start: {{ include "grafana/templates/_grafana-start.tpl" . | sha256sum }}
        checksum/grafana-initial-setup: {{ include "grafana/templates/_grafana-initial-setup.tpl" . | sha256sum }}
        checksum/helpers: {{ include "grafana/templates/_helpers.tpl" . | sha256sum }}
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: grafana-bin
          configMap:
            name: grafana-bin
        - name: grafana-etc
          configMap:
            name: grafana-etc
      containers:
        - name: "grafana"
          image: {{.Values.grafana.image}}:{{.Values.grafana.image_version}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          command:
            - /bin/bash
          args:
            - /grafana-bin/grafana-start
          ports:
            - name: nodejs
              containerPort: 3000
          volumeMounts:
            - name: grafana-bin
              mountPath: /grafana-bin
            - name: grafana-etc
              mountPath: /grafana-etc
