{{/* only deploy this seed if Ironic is installed in this region */}}
{{- if .Values.limes.clusters.ccloud -}}
{{- range .Values.limes.clusters.ccloud.capacitors -}}
{{- if eq .id "sapcc-ironic" -}}

apiVersion: "openstack.stable.sap.cc/v1"
kind: OpenstackSeed
metadata:
  name: limes-ironic-seed

spec:
  requires:
  - monsoon3/ironic-seed
  - limes/limes-seed

  domains:
    - name: ccadmin
      projects:
      - name: cloud_admin
        roles:
          - user: limes@Default
            role: cloud_baremetal_admin

{{- end -}}
{{- end -}}
{{- end -}}
