apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: blackbox-tests-api

data:
  os.password: {{ .Values.global.openstack.users.admin.password | b64enc }}
  vc.password: {{ .Values.global.master_password | b64enc }}