apiVersion: v1
kind: ConfigMap
metadata:
  name: manila-bin
  labels:
    system: openstack
    type: configuration
    component: manila

data:
  db-migrate: |
{{ .Files.Get "bin/db-migrate" | indent 4 }}
  common.sh: |
{{ include "common.sh" .| indent 4 }}
{{- if .Values.tempest_enabled }}
  manila-tempest-start: |
{{ .Files.Get "bin/manila-tempest-start" | indent 4 }}
{{- end }}
