{{- if .Values.maia.enabled }}
apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: maia-seed
  labels:
    component: maia
spec:
  requires:
#  - keystone-seed
  - monsoon3/domain-cc3test-seed
  - monsoon3/domain-ccadmin-seed

  roles:
  - monitoring_viewer
  - monitoring_admin

  services:
  - name: maia
    type: metrics
    description: Expose Prometheus metrics as multi-tenant OpenStack service
    endpoints:
    - interface: public
      region: {{.Values.global.region}}
      url: '{{.Values.maia.endpoint_protocol_public}}://{{.Values.maia.endpoint_host_public}}:{{.Values.maia.endpoint_port_public}}/api/v1'

  domains:
  - name: {{.Values.maia.service_user.user_domain_name}}
    users:
    - name: {{.Values.maia.service_user.name}}
      description: 'Maia API User'
      password: {{ .Values.maia.service_user.password | quote }}
      roles:
      - project: {{.Values.maia.service_user.project_name}}
        role: service

  - name: ccadmin
    projects:
    - name: master
      roles:
      - group: CCADMIN_CLOUD_ADMINS
        role: monitoring_admin
      - group: CCADMIN_DOMAIN_ADMINS
        role: monitoring_admin
      - group: CCADMIN_MONITORING_USERS
        role: monitoring_viewer
    groups:
    - name: CCADMIN_API_SUPPORT
      roles:
      - project: api_support
        role: monitoring_admin
      - project: api_tools
        role: monitoring_admin
      - domain: ccadmin
        role: monitoring_admin
        inherited: true
    - name: CCADMIN_COMPUTE_SUPPORT
      roles:
      - project: compute_support
        role: monitoring_admin
      - project: compute_tools
        role: monitoring_admin
      - domain: ccadmin
        role: monitoring_viewer
        inherited: true
    - name: CCADMIN_NETWORK_SUPPORT
      roles:
      - project: network_support
        role: monitoring_admin
      - project: network_tools
        role: monitoring_admin
      - domain: ccadmin
        role: monitoring_viewer
        inherited: true
    - name: CCADMIN_STORAGE_SUPPORT
      roles:
      - project: storage_support
        role: monitoring_admin
      - project: storage_tools
        role: monitoring_admin
      - domain: ccadmin
        role: monitoring_viewer
        inherited: true
    - name: CCADMIN_SERVICE_DESK
      roles:
      - project: service_desk
        role: monitoring_admin
      - domain: ccadmin
        role: monitoring_viewer
        inherited: true

  - name: bs
    groups:
    - name: BS_API_SUPPORT
      roles:
      - project: api_support
        role: monitoring_admin
      - domain: bs
        role: monitoring_admin
        inherited: true
    - name: BS_COMPUTE_SUPPORT
      roles:
      - project: compute_support
        role: monitoring_admin
      - domain: bs
        role: monitoring_viewer
        inherited: true
    - name: BS_NETWORK_SUPPORT
      roles:
      - project: network_support
        role: monitoring_admin
      - domain: bs
        role: monitoring_viewer
        inherited: true
    - name: BS_STORAGE_SUPPORT
      roles:
      - project: storage_support
        role: monitoring_admin
      - domain: bs
        role: monitoring_viewer
        inherited: true
    - name: BS_SERVICE_DESK
      roles:
      - project: service_desk
        role: monitoring_admin
      - domain: bs
        role: monitoring_viewer
        inherited: true

  - name: hcm
    groups:
    - name: HCM_API_SUPPORT
      roles:
      - project: api_support
        role: monitoring_admin
      - domain: hcm
        role: monitoring_admin
        inherited: true
    - name: HCM_COMPUTE_SUPPORT
      roles:
      - project: compute_support
        role: monitoring_admin
      - domain: hcm
        role: monitoring_viewer
        inherited: true
    - name: HCM_NETWORK_SUPPORT
      roles:
      - project: network_support
        role: monitoring_admin
      - domain: hcm
        role: monitoring_viewer
        inherited: true
    - name: HCM_STORAGE_SUPPORT
      roles:
      - project: storage_support
        role: monitoring_admin
      - domain: hcm
        role: monitoring_viewer
        inherited: true
    - name: HCM_SERVICE_DESK
      roles:
      - project: service_desk
        role: monitoring_admin
      - domain: hcm
        role: monitoring_viewer
        inherited: true

  - name: hcp03
    groups:
    - name: HCP03_API_SUPPORT
      roles:
      - project: api_support
        role: monitoring_admin
      - domain: hcp03
        role: monitoring_admin
        inherited: true
    - name: HCP03_COMPUTE_SUPPORT
      roles:
      - project: compute_support
        role: monitoring_admin
      - domain: hcp03
        role: monitoring_viewer
        inherited: true
    - name: HCP03_NETWORK_SUPPORT
      roles:
      - project: network_support
        role: monitoring_admin
      - domain: hcp03
        role: monitoring_viewer
        inherited: true
    - name: HCP03_STORAGE_SUPPORT
      roles:
      - project: storage_support
        role: monitoring_admin
      - domain: hcp03
        role: monitoring_viewer
        inherited: true
    - name: HCP03_SERVICE_DESK
      roles:
      - project: service_desk
        role: monitoring_admin
      - domain: hcp03
        role: monitoring_viewer
        inherited: true

  - name: hec
    groups:
    - name: HEC_API_SUPPORT
      roles:
      - project: api_support
        role: monitoring_admin
      - domain: hec
        role: monitoring_admin
        inherited: true
    - name: HEC_COMPUTE_SUPPORT
      roles:
      - project: compute_support
        role: monitoring_admin
      - domain: hec
        role: monitoring_viewer
        inherited: true
    - name: HEC_NETWORK_SUPPORT
      roles:
      - project: network_support
        role: monitoring_admin
      - domain: hec
        role: monitoring_viewer
        inherited: true
    - name: HEC_STORAGE_SUPPORT
      roles:
      - project: storage_support
        role: monitoring_admin
      - domain: hec
        role: monitoring_viewer
        inherited: true
    - name: HEC_SERVICE_DESK
      roles:
      - project: service_desk
        role: monitoring_admin
      - domain: hec
        role: monitoring_viewer
        inherited: true

  - name: monsoon3
    groups:
    - name: MONSOON3_API_SUPPORT
      roles:
      - project: api_support
        role: monitoring_admin
      - domain: monsoon3
        role: monitoring_admin
        inherited: true
    - name: MONSOON3_COMPUTE_SUPPORT
      roles:
      - project: compute_support
        role: monitoring_admin
      - domain: monsoon3
        role: monitoring_viewer
        inherited: true
    - name: MONSOON3_NETWORK_SUPPORT
      roles:
      - project: network_support
        role: monitoring_admin
      - domain: monsoon3
        role: monitoring_viewer
        inherited: true
    - name: MONSOON3_STORAGE_SUPPORT
      roles:
      - project: storage_support
        role: monitoring_admin
      - domain: monsoon3
        role: monitoring_viewer
        inherited: true
    - name: MONSOON3_SERVICE_DESK
      roles:
      - project: service_desk
        role: monitoring_admin
      - domain: monsoon3
        role: monitoring_viewer
        inherited: true

  - name: s4
    groups:
    - name: S4_API_SUPPORT
      roles:
      - project: api_support
        role: monitoring_admin
      - domain: s4
        role: monitoring_admin
        inherited: true
    - name: S4_COMPUTE_SUPPORT
      roles:
      - project: compute_support
        role: monitoring_admin
      - domain: s4
        role: monitoring_viewer
        inherited: true
    - name: S4_NETWORK_SUPPORT
      roles:
      - project: network_support
        role: monitoring_admin
      - domain: s4
        role: monitoring_viewer
        inherited: true
    - name: S4_STORAGE_SUPPORT
      roles:
      - project: storage_support
        role: monitoring_admin
      - domain: s4
        role: monitoring_viewer
        inherited: true
    - name: S4_SERVICE_DESK
      roles:
      - project: service_desk
        role: monitoring_admin
      - domain: s4
        role: monitoring_viewer
        inherited: true

  - name: wbs
    groups:
    - name: WBS_API_SUPPORT
      roles:
      - project: api_support
        role: monitoring_admin
      - domain: wbs
        role: monitoring_admin
        inherited: true
    - name: WBS_COMPUTE_SUPPORT
      roles:
      - project: compute_support
        role: monitoring_admin
      - domain: wbs
        role: monitoring_viewer
        inherited: true
    - name: WBS_NETWORK_SUPPORT
      roles:
      - project: network_support
        role: monitoring_admin
      - domain: wbs
        role: monitoring_viewer
        inherited: true
    - name: WBS_STORAGE_SUPPORT
      roles:
      - project: storage_support
        role: monitoring_admin
      - domain: wbs
        role: monitoring_viewer
        inherited: true
    - name: WBS_SERVICE_DESK
      roles:
      - project: service_desk
        role: monitoring_admin
      - domain: wbs
        role: monitoring_viewer
        inherited: true

  - name: cc3test
    groups:
    - name: CC3TEST_DOMAIN_ADMINS
      roles:
      - project: admin
        role: monitoring_admin

{{- end }}
