apiVersion: v1
kind: ConfigMap
metadata:
  name: neutron-etc
  labels:
    system: openstack
    type: configuration
    component: neutron

data:
  api-paste.ini: |
{{ include (print .Template.BasePath "/etc/_api-paste.ini.tpl") . | indent 4 }}
  dhcp-agent.ini: |
{{ include (print .Template.BasePath "/etc/_dhcp-agent.ini.tpl") . | indent 4 }}
  dnsmasq.conf: |
{{ include (print .Template.BasePath "/etc/_dnsmasq.conf.tpl") . | indent 4 }}
  l3-agent.ini: |
{{ include (print .Template.BasePath "/etc/_l3-agent.ini.tpl") . | indent 4 }}
  metadata-agent.ini: |
{{ include (print .Template.BasePath "/etc/_metadata-agent.ini.tpl") . | indent 4 }}
  ml2-conf.ini: |
{{ include (print .Template.BasePath "/etc/_ml2-conf.ini.tpl") . | indent 4 }}
  neutron.conf: |
{{ include (print .Template.BasePath "/etc/_neutron.conf.tpl") . | indent 4 }}
  neutron-lbaas.conf: |
{{ include (print .Template.BasePath "/etc/_neutron-lbaas.conf.tpl") . | indent 4 }}
  neutron-policy.json: |
{{ include (print .Template.BasePath "/etc/_neutron-policy.json.tpl") . | indent 4 }}
  rootwrap.conf: |
{{ include (print .Template.BasePath "/etc/_rootwrap.conf.tpl") . | indent 4 }}
  dhcp.filters: |
{{ include (print .Template.BasePath "/etc/_dhcp.filters.tpl") . | indent 4 }}
  l3.filters: |
{{ include (print .Template.BasePath "/etc/_l3.filters.tpl") . | indent 4 }}
  sudoers: |
{{ include (print .Template.BasePath "/etc/_sudoers.tpl") . | indent 4 }}
  logging.conf: |
{{ include "loggerIni" .Values.logging | indent 4 }}
{{- if .Values.audit.enabled }}
  neutron_audit_map.yaml: |
{{ include (print .Template.BasePath "/etc/_neutron_audit_map.yaml") . | indent 4 }}
{{- end }}
{{- if .Values.tempest.enabled }}
  tempest_accounts.yaml: |
{{ include (print .Template.BasePath "/etc/_tempest_accounts.yaml.tpl") . | indent 4 }}
  tempest_deployment_config.json: |
{{ include (print .Template.BasePath "/etc/_tempest_deployment_config.json.tpl") . | indent 4 }}
  tempest_expected_failures.yaml: |
{{- include (print .Template.BasePath "/etc/_tempest_expected_failures.yaml.tpl") . | indent 4 }}
  tempest_extra_options: |
{{ include (print .Template.BasePath "/etc/_tempest_extra_options.tpl") . | indent 4 }}
{{- end }}
{{- if .Values.watcher.enabled }}
  watcher.yaml: |
{{ include (print .Template.BasePath "/etc/_watcher.yaml.tpl") . | indent 4 }}
{{- end }}