{{ if $.Values.agent.enable_daemonset }}
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: neutron-agents
  labels:
    system: openstack
    application: neutron
    component: agent
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      component: agent
  template:
    metadata:
      labels:
        name: neutron-agents
{{ tuple . "neutron" "agent" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      nodeSelector:
        species: network
      tolerations:
        - key: "species"
          operator: "Equal"
          value: "network"
          effect: "NoSchedule"
      containers:
        - name: neutron-dhcp-agent
{{ tuple . "neutron-dhcp-agent" | include "helm-toolkit.snippets.network_container_agent" | indent 10 }}
          volumeMounts:
            - mountPath: /var/run
              name: run
            - mountPath: /neutron-etc
              name: neutron-etc
            - mountPath: /container.init
              name: container-init
            - mountPath: /run/netns
              name: host-run-netns
              mountPropagation: Bidirectional
        - name: neutron-metadata-agent
{{ tuple . "neutron-metadata-agent" | include "helm-toolkit.snippets.network_container_agent" | indent 10 }}
          volumeMounts:
            - mountPath: /var/run
              name: run
            - mountPath: /neutron-etc
              name: neutron-etc
            - mountPath: /container.init
              name: container-init
        - name: neutron-l3-agent
{{ tuple . "neutron-l3-agent" | include "helm-toolkit.snippets.network_container_agent" | indent 10 }}
          volumeMounts:
            - mountPath: /var/run
              name: run
            - mountPath: /lib/modules
              name: modules
              readOnly: true
            - mountPath: /neutron-etc
              name: neutron-etc
            - mountPath: /container.init
              name: container-init
        - name: neutron-ovs-agent
{{ tuple . "neutron-ovs-agent" | include "helm-toolkit.snippets.network_container_agent" | indent 10 }}
          volumeMounts:
            - mountPath: /var/run
              name: run
            - mountPath: /lib/modules
              name: modules
              readOnly: true
            - mountPath: /neutron-etc
              name: neutron-etc
            - mountPath: /container.init
              name: container-init
        - name: ovs
{{ tuple . "neutron-ovs" | include "helm-toolkit.snippets.network_container_agent" | indent 10 }}
          volumeMounts:
            - mountPath: /var/run
              name: run
            - mountPath: /lib/modules
              name: modules
              readOnly: true
            - mountPath: /container.init
              name: container-init
        - name: ovs-db
{{ tuple . "neutron-ovs-db" | include "helm-toolkit.snippets.network_container_agent" | indent 10 }}
          volumeMounts:
            - mountPath: /lib/modules
              name: modules
            - mountPath: /var/run
              name: run
            - mountPath: /container.init
              name: container-init
      volumes:
        - name : run
          emptyDir:
            medium: Memory
        - name : modules
          hostPath:
            path: /lib/modules
        - name: neutron-etc
          configMap:
            name: neutron-etc
        - name: container-init
          configMap:
            name: neutron-bin
            defaultMode: 0744
        - name: host-run-netns
          hostPath:
            path: /run/netns
{{ end }}
