global:
  region: DEFINED-AS-VALUE
  domain: DEFINED-AS-VALUE

  prometheus:
    image: prom/prometheus
    tag: v2.3.1

  prometheus-collector:
    configmap_name: prometheus-collector

  ipmi_exporter:
    enabled: false

  # placeholder. the full list of regions is set via the pipeline
  regions:
    - "staging"
