global:
  region: DEFINED-AS-VALUE
  domain: DEFINED-AS-VALUE

  prometheus:
    image: prom/prometheus
    tag: v2.3.1

  ipmi_exporter:
    enabled: false
    configmap_name: ipmi-sd

  # placeholder. the full list of regions is set via the pipeline
  regions:
    - "staging"
