apiVersion: "openstack.stable.sap.cc/v1"
kind: OpenstackSeed
metadata:
  name: hermes-seed
  labels:
    component: hermes
spec:
  requires:
  - monsoon3/domain-default-seed

  roles:
    - audit_viewer

  services:
    - name:        hermes
      type:        audit-data
      description: 'OpenStack Audit Data access'
      enabled:     true
      endpoints:
        - region:    '{{.Values.global.region}}'
          interface: public
          enabled:   true
          url:       '{{.Values.hermes.catalog_url}}'

  domains:
    - name: Default
      users:
        - name: 'hermes'
          description: Hermes Service
          password: '{{.Values.hermes.password}}'
          roles:
            - project: service
              role:    service
        - name: admin
          roles:
          - domain: Default
            role: audit_viewer
          - project: admin
            role: audit_viewer
      groups:
        - name: administrators
          roles:
            - domain: Default
              role: audit_viewer
            - project: admin
              role: audit_viewer

    - name: ccadmin
      projects:
        - name: master
          roles:
          - group: CCADMIN_CLOUD_ADMINS
            role: audit_viewer
          - group: CCADMIN_DOMAIN_ADMINS
            role: audit_viewer
          - group: CCADMIN_MONITORING_USERS
            role: audit_viewer
      groups:
        - name: CCADMIN_API_SUPPORT
          roles:
          - project: api_support
            role: audit_viewer
          - project: api_tools
            role: audit_viewer
          - domain: ccadmin
            role: audit_viewer
            inherited: true
        - name: CCADMIN_COMPUTE_SUPPORT
          roles:
          - project: compute_support
            role: audit_viewer
          - project: compute_tools
            role: audit_viewer
          - domain: ccadmin
            role: audit_viewer
            inherited: true
        - name: CCADMIN_NETWORK_SUPPORT
          roles:
          - project: network_support
            role: audit_viewer
          - project: network_tools
            role: audit_viewer
          - domain: ccadmin
            role: audit_viewer
            inherited: true
        - name: CCADMIN_STORAGE_SUPPORT
          roles:
          - project: storage_support
            role: audit_viewer
          - project: storage_tools
            role: audit_viewer
          - domain: ccadmin
            role: audit_viewer
            inherited: true
        - name: CCADMIN_SERVICE_DESK
          roles:
          - project: service_desk
            role: audit_viewer
          - domain: ccadmin
            role: audit_viewer
            inherited: true

    - name: bs
      groups:
      - name: BS_API_SUPPORT
        roles:
        - project: api_support
          role: audit_viewer
        - domain: bs
          role: audit_viewer
          inherited: true
      - name: BS_COMPUTE_SUPPORT
        roles:
        - project: compute_support
          role: audit_viewer
        - domain: bs
          role: audit_viewer
          inherited: true
      - name: BS_NETWORK_SUPPORT
        roles:
        - project: network_support
          role: audit_viewer
        - domain: bs
          role: audit_viewer
          inherited: true
      - name: BS_STORAGE_SUPPORT
        roles:
        - project: storage_support
          role: audit_viewer
        - domain: bs
          role: audit_viewer
          inherited: true
      - name: BS_SERVICE_DESK
        roles:
        - project: service_desk
          role: audit_viewer
        - domain: bs
          role: audit_viewer
          inherited: true

    - name: cp
      groups:
      - name: CP_API_SUPPORT
        roles:
        - project: api_support
          role: audit_viewer
        - domain: cp
          role: audit_viewer
          inherited: true
      - name: CP_COMPUTE_SUPPORT
        roles:
        - project: compute_support
          role: audit_viewer
        - domain: cp
          role: audit_viewer
          inherited: true
      - name: CP_NETWORK_SUPPORT
        roles:
        - project: network_support
          role: audit_viewer
        - domain: cp
          role: audit_viewer
          inherited: true
      - name: CP_STORAGE_SUPPORT
        roles:
        - project: storage_support
          role: audit_viewer
        - domain: cp
          role: audit_viewer
          inherited: true
      - name: CP_SERVICE_DESK
        roles:
        - project: service_desk
          role: audit_viewer
        - domain: cp
          role: audit_viewer
          inherited: true

    - name: hcm
      groups:
      - name: HCM_API_SUPPORT
        roles:
        - project: api_support
          role: audit_viewer
        - domain: hcm
          role: audit_viewer
          inherited: true
      - name: HCM_COMPUTE_SUPPORT
        roles:
        - project: compute_support
          role: audit_viewer
        - domain: hcm
          role: audit_viewer
          inherited: true
      - name: HCM_NETWORK_SUPPORT
        roles:
        - project: network_support
          role: audit_viewer
        - domain: hcm
          role: audit_viewer
          inherited: true
      - name: HCM_STORAGE_SUPPORT
        roles:
        - project: storage_support
          role: audit_viewer
        - domain: hcm
          role: audit_viewer
          inherited: true
      - name: HCM_SERVICE_DESK
        roles:
        - project: service_desk
          role: audit_viewer
        - domain: hcm
          role: audit_viewer
          inherited: true

    - name: hcp03
      groups:
      - name: HCP03_API_SUPPORT
        roles:
        - project: api_support
          role: audit_viewer
        - domain: hcp03
          role: audit_viewer
          inherited: true
      - name: HCP03_COMPUTE_SUPPORT
        roles:
        - project: compute_support
          role: audit_viewer
        - domain: hcp03
          role: audit_viewer
          inherited: true
      - name: HCP03_NETWORK_SUPPORT
        roles:
        - project: network_support
          role: audit_viewer
        - domain: hcp03
          role: audit_viewer
          inherited: true
      - name: HCP03_STORAGE_SUPPORT
        roles:
        - project: storage_support
          role: audit_viewer
        - domain: hcp03
          role: audit_viewer
          inherited: true
      - name: HCP03_SERVICE_DESK
        roles:
        - project: service_desk
          role: audit_viewer
        - domain: hcp03
          role: audit_viewer
          inherited: true

    - name: hec
      groups:
      - name: HEC_API_SUPPORT
        roles:
        - project: api_support
          role: audit_viewer
        - domain: hec
          role: audit_viewer
          inherited: true
      - name: HEC_COMPUTE_SUPPORT
        roles:
        - project: compute_support
          role: audit_viewer
        - domain: hec
          role: audit_viewer
          inherited: true
      - name: HEC_NETWORK_SUPPORT
        roles:
        - project: network_support
          role: audit_viewer
        - domain: hec
          role: audit_viewer
          inherited: true
      - name: HEC_STORAGE_SUPPORT
        roles:
        - project: storage_support
          role: audit_viewer
        - domain: hec
          role: audit_viewer
          inherited: true
      - name: HEC_SERVICE_DESK
        roles:
        - project: service_desk
          role: audit_viewer
        - domain: hec
          role: audit_viewer
          inherited: true

    - name: monsoon3
      groups:
      - name: MONSOON3_API_SUPPORT
        roles:
        - project: api_support
          role: audit_viewer
        - domain: monsoon3
          role: audit_viewer
          inherited: true
      - name: MONSOON3_COMPUTE_SUPPORT
        roles:
        - project: compute_support
          role: audit_viewer
        - domain: monsoon3
          role: audit_viewer
          inherited: true
      - name: MONSOON3_NETWORK_SUPPORT
        roles:
        - project: network_support
          role: audit_viewer
        - domain: monsoon3
          role: audit_viewer
          inherited: true
      - name: MONSOON3_STORAGE_SUPPORT
        roles:
        - project: storage_support
          role: audit_viewer
        - domain: monsoon3
          role: audit_viewer
          inherited: true
      - name: MONSOON3_SERVICE_DESK
        roles:
        - project: service_desk
          role: audit_viewer
        - domain: monsoon3
          role: audit_viewer
          inherited: true

    - name: s4
      groups:
      - name: S4_API_SUPPORT
        roles:
        - project: api_support
          role: audit_viewer
        - domain: s4
          role: audit_viewer
          inherited: true
      - name: S4_COMPUTE_SUPPORT
        roles:
        - project: compute_support
          role: audit_viewer
        - domain: s4
          role: audit_viewer
          inherited: true
      - name: S4_NETWORK_SUPPORT
        roles:
        - project: network_support
          role: audit_viewer
        - domain: s4
          role: audit_viewer
          inherited: true
      - name: S4_STORAGE_SUPPORT
        roles:
        - project: storage_support
          role: audit_viewer
        - domain: s4
          role: audit_viewer
          inherited: true
      - name: S4_SERVICE_DESK
        roles:
        - project: service_desk
          role: audit_viewer
        - domain: s4
          role: audit_viewer
          inherited: true

    - name: wbs
      groups:
      - name: WBS_API_SUPPORT
        roles:
        - project: api_support
          role: audit_viewer
        - domain: wbs
          role: audit_viewer
          inherited: true
      - name: WBS_COMPUTE_SUPPORT
        roles:
        - project: compute_support
          role: audit_viewer
        - domain: wbs
          role: audit_viewer
          inherited: true
      - name: WBS_NETWORK_SUPPORT
        roles:
        - project: network_support
          role: audit_viewer
        - domain: wbs
          role: audit_viewer
          inherited: true
      - name: WBS_STORAGE_SUPPORT
        roles:
        - project: storage_support
          role: audit_viewer
        - domain: wbs
          role: audit_viewer
          inherited: true
      - name: WBS_SERVICE_DESK
        roles:
        - project: service_desk
          role: audit_viewer
        - domain: wbs
          role: audit_viewer
          inherited: true

    - name: cc3test
      groups:
      - name: CC3TEST_DOMAIN_ADMINS
        roles:
        - project: admin
          role: audit_viewer