apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keystone-cron
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    system: openstack
    component: keystone
    type: operations
spec:
  replicas: {{ .Values.cron.replicas }}
  revisionHistoryLimit: {{ .Values.cron.upgrades.revisionHistory }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: keystone-cron
  template:
    metadata:
      labels:
        name: keystone-cron
        system: openstack
        component: keystone
        type: operations
      annotations:
        chart-version: {{.Chart.Version}}
        configmap-etc-hash: {{ include (print $.Template.BasePath "/configmap-etc.yaml") . | sha256sum }}
        configmap-bin-hash: {{ include (print $.Template.BasePath "/configmap-bin.yaml") . | sha256sum }}
    spec:
{{- if .Values.rbac.enabled }}
      serviceAccountName: keystone
{{- end }}
      containers:
        - name: keystone-cron
          image: {{ default "hub.global.cloud.sap" .Values.global.imageRegistry }}/{{ .Values.cron.image }}:{{ .Values.cron.imageTag }}
          imagePullPolicy: {{ .Values.cron.imagePullPolicy | default "IfNotPresent" | quote }}
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /scripts/cron"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
{{- if .Release.IsInstall }}
            - name: DEPENDENCY_JOBS
              value: keystone-job-migration,keystone-job-bootstrap
{{- end }}
            - name: DEPENDENCY_SERVICE
            {{- if .Values.postgresql.useOperator }}
              value: {{ .Release.Name }}-db
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: keystone-db.keystone.credentials
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: keystone-db.keystone.credentials
                  key: password
            {{ else }}
              value: {{ .Release.Name }}-postgresql
            {{- end }}
            {{- if .Values.sentry.enabled }}
            - name: SENTRY_DSN
            {{- if .Values.sentry.dsn }}
              value: {{ .Values.sentry.dsn | quote}}
            {{ else }}
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: keystone.DSN.python
            {{- end }}
            {{- end }}
          volumeMounts:
            - mountPath: /etc/keystone/keystone.conf
              subPath: keystone.conf
              name: keystone-etc
            - mountPath: /etc/keystone/logging.conf
              subPath: logging.conf
              name: keystone-etc
            - mountPath: /scripts
              name: keystone-bin
            - name: fernet
              mountPath: /fernet-keys
              readOnly: true
            - name: credential-keys
              mountPath: /credential-keys
              readOnly: true
          {{- if .Values.cron.resources.enabled }}
          resources:
            limits:
              cpu: {{ .Values.cron.resources.limits.cpu | quote }}
              memory: {{ .Values.cron.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.cron.resources.requests.cpu | quote }}
              memory: {{ .Values.cron.resources.requests.memory | quote }}
          {{- end }}
      volumes:
        - name: keystone-etc
          configMap:
            name: keystone-etc
        - name: keystone-bin
          configMap:
            name: keystone-bin
        - name: fernet
          secret:
            secretName: keystone-fernet
            defaultMode: 0755
        - name: credential-keys
          secret:
            secretName: keystone-credential-keys
            defaultMode: 0555
