image_version: DEFINED_IN_REGION_CHART
debug: false

image_version_auxiliary_statsd_exporter: 'v0.5.0'
image_version_auxiliary_alpine: '3.5'

auth_url: DEFINED_IN_REGION_CHART
password: DEFINED_IN_REGION_CHART

statsd_hostname: DEFINED_IN_REGION_CHART

# repos:
#   ubuntu:
#     #schedule: "15 8,20 * * *"
#     jobs:
#       - from:
#           url: DEFINED_IN_REGION_CHART
#         to:
#           container:     DEFINED_IN_REGION_CHART
#           object_prefix: DEFINED_IN_REGION_CHART
#   rhel:
#     transfer_workers: 2
#     cleanup_strategy: report
#     jobs:
#       - from:
#           url:  DEFINED_IN_REGION_CHART
#           cert: DEFINED_IN_REGION_CHART
#           key:  DEFINED_IN_REGION_CHART
#           ca:   DEFINED_IN_REGION_CHART
#         to:
#           container:     DEFINED_IN_REGION_CHART
#           object_prefix: DEFINED_IN_REGION_CHART
#
# client_certs:
#   rhel:
#     entitlement.pem: DEFINED_IN_REGION_CHART
#     entitlement-key.pem: DEFINED_IN_REGION_CHART
#     ca.pem: DEFINED_IN_REGION_CHART
