apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ template "blackbox-exporter.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}

spec:
  revisionHistoryLimit: 5
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "blackbox-exporter.name" . }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: {{ .Values.service.port | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          args:
            - --config.file=/etc/blackbox-exporter/blackbox.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/blackbox-exporter
      volumes:
        - name: config
          configMap:
            name: {{ .Chart.Name }}
