apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ntp-exporter
spec:
  minReadySeconds: 5
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      name: ntp-exporter
      labels:
        app: ntp-exporter
    spec:
      tolerations:
      - key: "species"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name:  ntp-exporter
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
            - "-ntp.server={{ .Values.ntp.server }}"
          ports:
            - name: metrics
              containerPort: 9100
              hostPort: 9101
          resources:
            requests:
              memory: 40Mi
              cpu: 10m
            limits:
              memory: 100Mi
              cpu: 20m
