kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: designate-mdns
  labels:
    system: openstack
    type: backend
    component: designate
spec:
  replicas: {{ .Values.pod.replicas.mdns }}
  revisionHistoryLimit: {{ .Values.pod.lifecycle.upgrades.deployments.revision_history }}
  strategy:
    type: {{ .Values.pod.lifecycle.upgrades.deployments.pod_replacement_strategy }}
    {{ if eq .Values.pod.lifecycle.upgrades.deployments.pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.pod.lifecycle.upgrades.deployments.rolling_update.max_unavailable }}
      maxSurge: {{ .Values.pod.lifecycle.upgrades.deployments.rolling_update.max_surge }}
    {{ end }}
  selector:
    matchLabels:
      app: designate-mdns
  template:
    metadata:
      labels:
        app: designate-mdns
      annotations:
        configmap-etc-hash: {{ include (print $.Template.BasePath "/etc-configmap.yaml") . | sha256sum }}
        configmap-bin-hash: {{ include (print $.Template.BasePath "/bin-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: designate-mdns
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-designate-mdns:{{.Values.image_version_designate_mdns}}
          imagePullPolicy: IfNotPresent
          command:
            - bash
          args:
            - /container.init/designate-mdns-start
          env:
            - name: DEBUG_CONTAINER
              value: "false"
            {{- if .Values.sentry.enabled }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: designate.DSN.python
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: {{.Values.global.designate_mdns_port_public}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          ports:
            - name: designate-mdns
              containerPort: {{.Values.global.designate_mdns_port_public}}
          volumeMounts:
            - mountPath: /designate-etc
              name: designate-etc
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: designate-etc
          configMap:
            name: designate-etc
        - name: container-init
          configMap:
            name: designate-bin
            defaultMode: 0755
