apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: prometheus-global-sso-cert

data:
  prometheus_sso.crt: {{ default "" .Values.kubernikus.authentication.tls_cert | b64enc | quote }}
  prometheus_sso.key: {{ default "" .Values.kubernikus.authentication.tls_key | b64enc | quote }}
