---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-etc
  labels:
    system: openstack
    service: logging
    component: configuration

data:
  elasticsearch.yml: |
{{ include "elk/templates/etc/_elasticsearch.yml.tpl" . | indent 4 }}
  readonlyrest.yml: |
{{ include "elk/templates/etc/_readonlyrest.yml.tpl" . | indent 4 }}
  log4j2.properties: |
{{ include "elk/templates/etc/_log4j2.properties.tpl" . | indent 4 }}
  jvm.options: |
{{ include "elk/templates/etc/_jvm.options.tpl" . | indent 4 }}
