apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: kibana
  namespace: elk
  annotations:
    vice-president: {{ default false .Values.vice_president | quote }}
    # this is for kibana sso cert evaluation
  {{- if .Values.kibana.auth.tls_client_auth.enabled}}
    ingress.kubernetes.io/auth-tls-secret: {{ default "" .Values.kibana.auth.tls_client_auth.secret }}
    ingress.kubernetes.io/auth-tls-verify-depth: "3"
    ingress.kubernetes.io/auth-tls-verify-client: "optional"
  {{ end }}

spec:
  tls:
     - secretName: kibana
       hosts: [{{.Values.elk_kibana_endpoint_host_public}}]
  rules:
    - host: {{.Values.elk_kibana_endpoint_host_public}}
      http:
        paths:
        - path: /
          backend:
            serviceName: kibana
            servicePort: {{.Values.elk_kibana_port_public}}
