apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: elk
  labels:
    system: openstack
    service: logging

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        component: kibana
      annotations:
        checksum/elk-templates-kibana-etc-configmap.yaml: {{ include "elk/templates/kibana-etc-configmap.yaml" . | sha256sum }}
        checksum/elk-templates-kibana-bin-configmap.yaml: {{ include "elk/templates/kibana-bin-configmap.yaml" . | sha256sum }}
        checksum/kibana.yml.tpl: {{ include "elk/templates/etc/_kibana.yml.tpl" . | sha256sum }}
        checksum/kibana-start.tpl: {{ include "elk/templates/bin/_kibana-start.tpl" . | sha256sum }}
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: kibana-bin
          configMap:
            name: kibana-bin
        - name: kibana-etc
          configMap:
            name: kibana-etc
      containers:
        - name: kibana
          image: {{.Values.docker_repo}}/elk-kibana:{{.Values.elk_image_version_kibana}}
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/dumb-init", "/bin/bash", "/kibana-bin/kibana-start"]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEPENDENCY_SERVICE
              value: "es-client.elk"
          ports:
            - name: nodejs
              containerPort: {{.Values.elk_kibana_port_public}}
          volumeMounts:
            - mountPath: /kibana-bin
              name: kibana-bin
            - mountPath: /kibana-etc
              name: kibana-etc
