apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alertmanager

data:
  alertmanager.yml: |
    global:
      resolve_timeout: 16m

    templates: 
      - ./*.tmpl

    inhibit_rules:
    # Mute warnings for which also a critical alert exists.
    # Per context and region.
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['context']
    - source_match:
        severity: 'critical|warning'
      target_match:
        severity: 'info'
      equal: ['context']

    route:
      group_by: ['region', 'alertname']
      group_wait: 1m
      group_interval: 7m
      repeat_interval: 12h
      receiver: dev-null

      routes:
      - receiver: dev-null
        continue: true
        match_re:
          region: staging
      - receiver: kubernetes-info
        continue: true
        match_re:
          tier: kubernetes
          region: ^[a-zA-Z]+\-[a-zA-Z]+\-[0-9]$|admin
        routes:
        - receiver: 'kubernetes-warning'
          continue: true
          match:
            severity: warning
        - receiver: 'kubernetes-critical'
          continue: true
          match:
            severity: critical
      - receiver: kubernikus-info
        continue: true
        match_re:
          tier: kubernikus
          region: ^[a-zA-Z]+\-[a-zA-Z]+\-[0-9]$|admin
        routes:
        - receiver: 'kubernikus-warning'
          continue: true
          match:
            severity: warning
        - receiver: 'kubernikus-critical'
          continue: true
          match:
            severity: critical
      - receiver: openstack-info
        continue: true
        match_re:
          tier: openstack
          region: ^[a-zA-Z]+\-[a-zA-Z]+\-[0-9]$|admin
        routes:
        - receiver: 'openstack-warning'
          continue: true
          match:
            severity: warning
        - receiver: 'openstack-critical'
          continue: true
          match:
            severity: critical
      {{- range tuple "arc" "backup" "cinder" "designate" "elektra" "elk" "ironic" "keystone" "limes" "lyra" "maia" "manila" "neutron" "nova" "swift" }}
      - receiver: openstack-{{ . }}
        continue: true
        match_re:
          service: {{ . }}
          tier: openstack
          region: ^[a-zA-Z]+\-[a-zA-Z]+\-[0-9]$|admin
      {{- end }}
      - receiver: pagerduty
        continue: true
        match_re:
          region: ^[a-p,r-zA-P,R-Z]+\-[a-zA-Z]+\-[0-9]$|admin
        match:
          severity: critical

    receivers:
    {{- range tuple "dev-null" "kubernetes-info" "kubernetes-warning" "kubernetes-critical" }}
    - name: {{ . }}
      slack_configs:
      - api_url: {{ default "MISSING" $.Values.slack_webhook_url | quote }}
        username: "Kubernetes Control Plane"
        channel: "#{{ . }}"
        title: {{"'{{template \"slack.sapcc.title\" . }}'"}}
        title_link: {{"'{{template \"slack.sapcc.titlelink\" . }}'"}}
        text: {{"'{{template \"slack.sapcc.text\" . }}'"}}
        pretext: {{"'{{template \"slack.sapcc.pretext\" . }}'"}}
        icon_emoji: {{"'{{template \"slack.sapcc.iconemoji\" . }}'"}}
        send_resolved: true
    {{- end }}
    {{- range tuple "kubernikus-info" "kubernikus-warning" "kubernikus-critical" }}
    - name: {{ . }}
      slack_configs:
      - api_url: {{ default "MISSING" $.Values.slack_webhook_url | quote }}
        username: "Kubernikus Control Plane"
        channel: "#{{ . }}"
        title: {{"'{{template \"slack.sapcc.title\" . }}'"}}
        title_link: {{"'{{template \"slack.sapcc.titlelink\" . }}'"}}
        text: {{"'{{template \"slack.sapcc.text\" . }}'"}}
        pretext: {{"'{{template \"slack.sapcc.pretext\" . }}'"}}
        icon_emoji: {{"'{{template \"slack.sapcc.iconemoji\" . }}'"}}
        send_resolved: true
    {{- end }}
    {{- range tuple "info" "warning" "critical" "arc" "backup" "cinder" "designate" "elektra" "elk" "ironic" "keystone" "limes" "lyra" "maia" "manila" "neutron" "nova" "swift" }}
    - name: openstack-{{ . }}
      slack_configs:
      - api_url: {{ default "MISSING" $.Values.slack_webhook_url | quote }}
        username: "OpenStack Control Plane"
        channel: "#openstack-{{ . }}"
        title: {{"'{{template \"slack.sapcc.title\" . }}'"}}
        title_link: {{"'{{template \"slack.sapcc.titlelink\" . }}'"}}
        text: {{"'{{template \"slack.sapcc.text\" . }}'"}}
        pretext: {{"'{{template \"slack.sapcc.pretext\" . }}'"}}
        icon_emoji: {{"'{{template \"slack.sapcc.iconemoji\" . }}'"}}
        send_resolved: true 
    {{- end }}
    - name: pagerduty
      pagerduty_configs:
      - service_key: {{ default "" .Values.pagerduty.service_key }}
        description: {{"'{{ template \"pagerduty.sapcc.description\" . }}'"}}
        component: {{"'{{template \"pagerduty.sapcc.tier\" . }}'"}}
        group: {{"'{{template \"pagerduty.sapcc.service\" . }}'"}}
        details:
          Details: {{"'{{template \"pagerduty.sapcc.details\" . }}'"}}
          Region: {{"'{{template \"pagerduty.sapcc.region\" . }}'"}}
          Tier: {{"'{{template \"pagerduty.sapcc.tier\" . }}'"}}
          Service: {{"'{{template \"pagerduty.sapcc.service\" . }}'"}}
          Context: {{"'{{template \"pagerduty.sapcc.context\" . }}'"}}
          Prometheus: {{"'{{template \"pagerduty.sapcc.prometheus\" . }}'"}}
          Dashboard: {{"'{{template \"pagerduty.sapcc.dashboard\" . }}'"}}
          Sentry: {{"'{{template \"pagerduty.sapcc.sentry\" . }}'"}}
          Playbook: {{"'{{template \"pagerduty.sapcc.playbook\" . }}'"}}
          firing: {{"'{{ template \"pagerduty.sapcc.firing\" . }}'"}}

  {{- $files := .Files }}
  {{ range tuple "slack.tmpl" "pagerduty.tmpl" }}
  {{ . }}: |
{{ $files.Get . | indent 4 }}
  {{- end }}
