{{- if .Values.ipmi_service_discovery.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ipmi-service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipmi-sd
      type: service-discovery
  template:
    metadata:
      labels:
        app: ipmi-sd
        type: service-discovery
    spec:
      containers:
      - name: ipmi-sd
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.ipmi_service_discovery.image }}:{{ .Values.ipmi_service_discovery.tag }}"
        env:
        - name: APP_ENV
          value: "{{ .Values.ipmi_service_discovery.app_env }}"
        - name: OS_AUTH_URL
          value: "{{ .Values.ipmi_service_discovery.os_auth_url }}"
        - name: OS_USERNAME
          value: "{{ .Values.ipmi_service_discovery.os_username }}"
        - name: OS_PASSWORD
          value: "{{ .Values.ipmi_service_discovery.os_password }}"
        - name: OS_USER_DOMAIN_NAME
          value: "{{ .Values.ipmi_service_discovery.os_user_domain_name }}"
        - name: OS_PROJECT_NAME
          value: "{{ .Values.ipmi_service_discovery.os_project_name }}"
        - name: OS_PROJECT_DOMAIN_NAME
          value: "{{ .Values.ipmi_service_discovery.os_project_domain_name }}"
        - name: OS_PROM_CONFIGMAP_NAME
          value: "{{ .Values.ipmi_service_discovery.configmap_name }}"
{{- end }}
