## postgres-operator image repository
image: monsoon/postgres-operator
imageTag: "20180928130414"

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:

replicas: 1

operator:
  # spilo image
  image: hub.global.cloud.sap/monsoon/spilo
  imageTag: "20181013140057"
  workers: 8
  resync_period: 3m
  pod_label_wait_timeout: 5m
  

exporter:
  image: postgres-operator-exporter
  tag: v1.0.2

serviceaccount:
  create: true
  name: postgres-operator

rbac:
  create: false

