## postgres-operator image repository
image: monsoon/postgres-operator
imageTag: "20180710151824"

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:

replicas: 1

operator:
  # spilo image
  image: hub.global.cloud.sap/monsoon/spilo
  imageTag: "20180629092110"

serviceaccount:
  create: true
  name: postgres-operator

rbac:
  create: false

