{{- if .Values.omnitruck.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-omnitruck
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.omnitruck.internalPort }}
    targetPort: {{ .Values.omnitruck.internalPort }}
  selector:
    app: {{.Release.Name}}-omnitruck
{{- end  }}
