# Default values for mosquitto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#tls:
#  caCertificate:
#  privateKey:
#  certificate:

tls:
  enabled: false
  #caCertificate:
  #privateKey:
  #certificate:

image:
  repository: sapcc/mosquitto
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: mosquitto
  type: ClusterIP
  externalPort: 8883
  internalPort: 8883
  externalIPs: [1.2.3.4]
metrics:
  enabled: false #TODO figure out how to connect using tls
  port: 9234
  image:
    repository: sapcc/mosquitto-exporter
    tag: 0.3.0
    pullPolicy: IfNotPresent
