apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: openstack-seeder
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.upgrades.revisionHistory }}
  strategy:
    type: {{ .Values.upgrades.podReplacementStrategy }}
    {{ if eq .Values.upgrades.podReplacementStrategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.upgrades.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.upgrades.rollingUpdate.maxSurge }}
    {{ end }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        name: openstack-seeder
      annotations:
        checksum/bin-configmap.conf: {{ include (print $.Chart.Name "/templates/bin-configmap.yaml") . | sha256sum }}
    spec:
{{- if .Values.rbac.enabled }}
      serviceAccountName: openstack-seeder
{{- end }}
      containers:
        - name: operator
{{- if typeIs "float64" .Values.imageTag  }}{{/* https://github.com/kubernetes/helm/issues/1707 */}}
          image: {{ default "hub.global.cloud.sap" .Values.global.imageRegistry }}/{{ .Values.image }}:{{ .Values.imageTag | printf "%0.f" }}
{{- else }}
          image: {{ default "hub.global.cloud.sap" .Values.global.imageRegistry }}/{{ .Values.image }}:{{ .Values.imageTag }}
{{- end }}

          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" | quote }}
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /scripts/start"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
          volumeMounts:
            - mountPath: /scripts
              name: scripts
      volumes:
        - name: scripts
          configMap:
            name: openstack-seeder-bin
