kind: Ingress
apiVersion: extensions/v1beta1

metadata:
  name: keppel-api
  annotations:
    vice-president: "true"

spec:
  tls:
    - secretName: keppel-api
      hosts: [ keppel.{{ .Values.global.region }}.{{ .Values.global.tld }} ]
  rules:
    - host: keppel.{{ .Values.global.region }}.{{ .Values.global.tld }}
      http:
        paths:
          - path: /
            backend:
              serviceName: keppel-api
              servicePort: 80
