kind: Service
apiVersion: v1

metadata:
  name: keppel-api
  # TODO: Prometheus metrics
  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: "80"

spec:
  selector:
    app: keppel-api
  ports:
    - port: 80
