apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: elektra-seed
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  requires:
  - monsoon3/domain-default-seed
  - monsoon3/domain-bs-seed
  - monsoon3/domain-cp-seed
  - monsoon3/domain-ccadmin-seed
  - monsoon3/domain-fsn-seed
  - monsoon3/domain-hcp03-seed
  - monsoon3/domain-hcm-seed
  - monsoon3/domain-hec-seed
  - monsoon3/domain-monsoon3-seed
  - monsoon3/domain-s4-seed
{{- if .Values.tempest.enabled }}
  - monsoon3/domain-tempest-seed
{{- end }}
  - monsoon3/domain-wbs-seed
  - monsoon3/domain-cc3test-seed

  roles:
  - cloud_compute_admin
  - cloud_network_admin
  - cloud_dns_admin
  - cloud_image_admin
  - cloud_keymanager_admin
  - cloud_resource_admin
  - cloud_sharedfilesystem_admin
  - cloud_volume_admin
  - cloud_baremetal_admin
  - cloud_support_tools_viewer

  domains:
  - name: Default
    users:
    - name: {{ default "dashboard" .Values.monsoon_openstack_auth_api_userid | quote }}
      description: 'Dashboard Service'
      password: {{ .Values.monsoon_openstack_auth_api_password | quote }}
      roles:
      - project: service
        role: service
      - project: cloud_admin@ccadmin
        role: admin
      - project: cloud_admin@ccadmin
        role: cloud_compute_admin
      - project: cloud_admin@ccadmin
        role: cloud_dns_admin
      - project: cloud_admin@ccadmin
        role: cloud_image_admin
      - project: cloud_admin@ccadmin
        role: cloud_keymanager_admin
      - project: cloud_admin@ccadmin
        role: cloud_network_admin
      - project: cloud_admin@ccadmin
        role: cloud_resource_admin
      - project: cloud_admin@ccadmin
        role: cloud_sharedfilesystem_admin
      - project: cloud_admin@ccadmin
        role: cloud_volume_admin
      - project: cloud_admin@ccadmin
        role: cloud_baremetal_admin
      - domain: Default
        role: admin
      - domain: ccadmin
        role: admin
      - domain: cp
        role: admin
      - domain: bs
        role: admin
      - domain: fsn
        role: admin
      - domain: hcp03
        role: admin
      - domain: hcm
        role: admin
      - domain: hec
        role: admin
      - domain: monsoon3
        role: admin
      - domain: s4
        role: admin
{{- if .Values.tempest.enabled }}
      - domain: tempest
        role: admin
{{- end }}
      - domain: wbs
        role: admin
      - domain: cc3test
        role: admin


  - name: ccadmin
    groups:
    - name: CCADMIN_API_SUPPORT
      roles:
      - domain: ccadmin
        role: cloud_support_tools_viewer
      - domain: ccadmin
        role: cloud_support_tools_viewer
        inherited: true
    - name: CCADMIN_COMPUTE_SUPPORT
      roles:
      - domain: ccadmin
        role: cloud_support_tools_viewer
      - domain: ccadmin
        role: cloud_support_tools_viewer
        inherited: true
    - name: CCADMIN_NETWORK_SUPPORT
      roles:
      - domain: ccadmin
        role: cloud_support_tools_viewer
      - domain: ccadmin
        role: cloud_support_tools_viewer
        inherited: true
    - name: CCADMIN_STORAGE_SUPPORT
      roles:
      - domain: ccadmin
        role: cloud_support_tools_viewer
      - domain: ccadmin
        role: cloud_support_tools_viewer
        inherited: true
    - name: CCADMIN_SERVICE_DESK
      roles:
      - domain: ccadmin
        role: cloud_support_tools_viewer
      - domain: ccadmin
        role: cloud_support_tools_viewer
        inherited: true

  - name: bs
    groups:
    - name: BS_API_SUPPORT
      roles:
      - domain: bs
        role: cloud_support_tools_viewer
      - domain: bs
        role: cloud_support_tools_viewer
        inherited: true
    - name: BS_COMPUTE_SUPPORT
      roles:
      - domain: bs
        role: cloud_support_tools_viewer
      - domain: bs
        role: cloud_support_tools_viewer
        inherited: true
    - name: BS_NETWORK_SUPPORT
      roles:
      - domain: bs
        role: cloud_support_tools_viewer
      - domain: bs
        role: cloud_support_tools_viewer
        inherited: true
    - name: BS_STORAGE_SUPPORT
      roles:
      - domain: bs
        role: cloud_support_tools_viewer
      - domain: bs
        role: cloud_support_tools_viewer
        inherited: true
    - name: BS_SERVICE_DESK
      roles:
      - domain: bs
        role: cloud_support_tools_viewer
      - domain: bs
        role: cloud_support_tools_viewer
        inherited: true

  - name: cp
    groups:
    - name: CP_API_SUPPORT
      roles:
      - domain: cp
        role: cloud_support_tools_viewer
      - domain: cp
        role: cloud_support_tools_viewer
        inherited: true
    - name: CP_COMPUTE_SUPPORT
      roles:
      - domain: cp
        role: cloud_support_tools_viewer
      - domain: cp
        role: cloud_support_tools_viewer
        inherited: true
    - name: CP_NETWORK_SUPPORT
      roles:
      - domain: cp
        role: cloud_support_tools_viewer
      - domain: cp
        role: cloud_support_tools_viewer
        inherited: true
    - name: CP_STORAGE_SUPPORT
      roles:
      - domain: cp
        role: cloud_support_tools_viewer
      - domain: cp
        role: cloud_support_tools_viewer
        inherited: true
    - name: CP_SERVICE_DESK
      roles:
      - domain: cp
        role: cloud_support_tools_viewer
      - domain: cp
        role: cloud_support_tools_viewer
        inherited: true

  - name: fsn
    groups:
    - name: FSN_API_SUPPORT
      roles:
      - domain: fsn
        role: cloud_support_tools_viewer
      - domain: fsn
        role: cloud_support_tools_viewer
        inherited: true
    - name: FSN_COMPUTE_SUPPORT
      roles:
      - domain: fsn
        role: cloud_support_tools_viewer
      - domain: fsn
        role: cloud_support_tools_viewer
        inherited: true
    - name: FSN_NETWORK_SUPPORT
      roles:
      - domain: fsn
        role: cloud_support_tools_viewer
      - domain: fsn
        role: cloud_support_tools_viewer
        inherited: true
    - name: FSN_STORAGE_SUPPORT
      roles:
      - domain: fsn
        role: cloud_support_tools_viewer
      - domain: fsn
        role: cloud_support_tools_viewer
        inherited: true
    - name: FSN_SERVICE_DESK
      roles:
      - domain: fsn
        role: cloud_support_tools_viewer
      - domain: fsn
        role: cloud_support_tools_viewer
        inherited: true

  - name: hcm
    groups:
    - name: HCM_API_SUPPORT
      roles:
      - domain: hcm
        role: cloud_support_tools_viewer
      - domain: hcm
        role: cloud_support_tools_viewer
        inherited: true
    - name: HCM_COMPUTE_SUPPORT
      roles:
      - domain: hcm
        role: cloud_support_tools_viewer
      - domain: hcm
        role: cloud_support_tools_viewer
        inherited: true
    - name: HCM_NETWORK_SUPPORT
      roles:
      - domain: hcm
        role: cloud_support_tools_viewer
      - domain: hcm
        role: cloud_support_tools_viewer
        inherited: true
    - name: HCM_STORAGE_SUPPORT
      roles:
      - domain: hcm
        role: cloud_support_tools_viewer
      - domain: hcm
        role: cloud_support_tools_viewer
        inherited: true
    - name: HCM_SERVICE_DESK
      roles:
      - domain: hcm
        role: cloud_support_tools_viewer
      - domain: hcm
        role: cloud_support_tools_viewer
        inherited: true

  - name: hcp03
    groups:
    - name: HCP03_API_SUPPORT
      roles:
      - domain: hcp03
        role: cloud_support_tools_viewer
      - domain: hcp03
        role: cloud_support_tools_viewer
        inherited: true
    - name: HCP03_COMPUTE_SUPPORT
      roles:
      - domain: hcp03
        role: cloud_support_tools_viewer
      - domain: hcp03
        role: cloud_support_tools_viewer
        inherited: true
    - name: HCP03_NETWORK_SUPPORT
      roles:
      - domain: hcp03
        role: cloud_support_tools_viewer
      - domain: hcp03
        role: cloud_support_tools_viewer
        inherited: true
    - name: HCP03_STORAGE_SUPPORT
      roles:
      - domain: hcp03
        role: cloud_support_tools_viewer
      - domain: hcp03
        role: cloud_support_tools_viewer
        inherited: true
    - name: HCP03_SERVICE_DESK
      roles:
      - domain: hcp03
        role: cloud_support_tools_viewer
      - domain: hcp03
        role: cloud_support_tools_viewer
        inherited: true

  - name: hec
    groups:
    - name: HEC_API_SUPPORT
      roles:
      - domain: hec
        role: cloud_support_tools_viewer
      - domain: hec
        role: cloud_support_tools_viewer
        inherited: true
    - name: HEC_COMPUTE_SUPPORT
      roles:
      - domain: hec
        role: cloud_support_tools_viewer
      - domain: hec
        role: cloud_support_tools_viewer
        inherited: true
    - name: HEC_NETWORK_SUPPORT
      roles:
      - domain: hec
        role: cloud_support_tools_viewer
      - domain: hec
        role: cloud_support_tools_viewer
        inherited: true
    - name: HEC_STORAGE_SUPPORT
      roles:
      - domain: hec
        role: cloud_support_tools_viewer
      - domain: hec
        role: cloud_support_tools_viewer
        inherited: true
    - name: HEC_SERVICE_DESK
      roles:
      - domain: hec
        role: cloud_support_tools_viewer
      - domain: hec
        role: cloud_support_tools_viewer
        inherited: true

  - name: monsoon3
    groups:
    - name: MONSOON3_API_SUPPORT
      roles:
      - domain: monsoon3
        role: cloud_support_tools_viewer
      - domain: monsoon3
        role: cloud_support_tools_viewer
        inherited: true
    - name: MONSOON3_COMPUTE_SUPPORT
      roles:
      - domain: monsoon3
        role: cloud_support_tools_viewer
      - domain: monsoon3
        role: cloud_support_tools_viewer
        inherited: true
    - name: MONSOON3_NETWORK_SUPPORT
      roles:
      - domain: monsoon3
        role: cloud_support_tools_viewer
      - domain: monsoon3
        role: cloud_support_tools_viewer
        inherited: true
    - name: MONSOON3_STORAGE_SUPPORT
      roles:
      - domain: monsoon3
        role: cloud_support_tools_viewer
      - domain: monsoon3
        role: cloud_support_tools_viewer
        inherited: true
    - name: MONSOON3_SERVICE_DESK
      roles:
      - domain: monsoon3
        role: cloud_support_tools_viewer
      - domain: monsoon3
        role: cloud_support_tools_viewer
        inherited: true

  - name: s4
    groups:
    - name: S4_API_SUPPORT
      roles:
      - domain: s4
        role: cloud_support_tools_viewer
      - domain: s4
        role: cloud_support_tools_viewer
        inherited: true
    - name: S4_COMPUTE_SUPPORT
      roles:
      - domain: s4
        role: cloud_support_tools_viewer
      - domain: s4
        role: cloud_support_tools_viewer
        inherited: true
    - name: S4_NETWORK_SUPPORT
      roles:
      - domain: s4
        role: cloud_support_tools_viewer
      - domain: s4
        role: cloud_support_tools_viewer
        inherited: true
    - name: S4_STORAGE_SUPPORT
      roles:
      - domain: s4
        role: cloud_support_tools_viewer
      - domain: s4
        role: cloud_support_tools_viewer
        inherited: true
    - name: S4_SERVICE_DESK
      roles:
      - domain: s4
        role: cloud_support_tools_viewer
      - domain: s4
        role: cloud_support_tools_viewer
        inherited: true

  - name: wbs
    groups:
    - name: WBS_API_SUPPORT
      roles:
      - domain: wbs
        role: cloud_support_tools_viewer
      - domain: wbs
        role: cloud_support_tools_viewer
        inherited: true
    - name: WBS_COMPUTE_SUPPORT
      roles:
      - domain: wbs
        role: cloud_support_tools_viewer
      - domain: wbs
        role: cloud_support_tools_viewer
        inherited: true
    - name: WBS_NETWORK_SUPPORT
      roles:
      - domain: wbs
        role: cloud_support_tools_viewer
      - domain: wbs
        role: cloud_support_tools_viewer
        inherited: true
    - name: WBS_STORAGE_SUPPORT
      roles:
      - domain: wbs
        role: cloud_support_tools_viewer
      - domain: wbs
        role: cloud_support_tools_viewer
        inherited: true
    - name: WBS_SERVICE_DESK
      roles:
      - domain: wbs
        role: cloud_support_tools_viewer
      - domain: wbs
        role: cloud_support_tools_viewer
        inherited: true
