kind: Service
apiVersion: v1

metadata:
  name: blackbox-tests-integrity
  annotations:
    "prometheus.io/scrape": "true"
    "prometheus.io/port": "{{.Values.global.port_metrics}}"

spec:
  selector:
    name: blackbox-tests-integrity
  ports:
    - port: {{ .Values.global.port_metrics }}