kind: Service
apiVersion: v1

metadata:
  name: cinder-api
  labels:
    system: openstack
    type: api
    component: cinder
  annotations:
    prometheus.io/scrape: "true"
    maia.io/scrape: "true"
    prometheus.io/port: {{.Values.port_metrics | quote }}
spec:
  selector:
    name: cinder-api
  ports:
    - name: cinder-api
      port: {{ .Values.cinderApiPortInternal | quote }}
