{{- if .Values.dbPassword }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cinder-db-maintain
  labels:
    system: openstack
    type: configuration
    component: database

data:
  db-maintain.sql: |
    ALTER ROLE {{.Values.dbUser}} WITH ENCRYPTED PASSWORD '{{.Values.dbPassword}}';
    ALTER ROLE {{ .Values.postgresql.postgresUser }} WITH ENCRYPTED PASSWORD '{{ .Values.postgresql.postgresPassword }}';
{{- end }}
