apiVersion: vcenter-operator.stable.sap.cc/v1
kind: VCenterTemplate
metadata:
  name: 'vcenter-datacenter-cinder-deployment'
  scope: 'datacenter'
template: |{{`
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: cinder-volume-vmware-{{ name }}
    labels:
      system: openstack
      type: backend
      component: cinder
  spec:
    replicas: 1
    revisionHistoryLimit: 5
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    selector:
      matchLabels:
          name: cinder-volume-vmware-{{ name }}
    template:
      metadata:
        labels:
          application: cinder
          component: volume-vmware
          name: cinder-volume-vmware-{{ name }}
      spec:
        hostname: cinder-volume-vmware-{{ name }}
        containers:
        - name: cinder-volume-vmware-{{ name }}
          image: `}}{{.Values.global.imageRegistry}}/{{.Values.global.image_namespace}}/ubuntu-source-cinder-scheduler:{{.Values.imageVersionCinderScheduler | default .Values.imageVersion | required "Please set cinder.imageVersion or similar" }}{{`
          imagePullPolicy: IfNotPresent
          command:
          - dumb-init
          - kubernetes-entrypoint
          env:
          - name: COMMAND
            value: 'cinder-volume'
          - name: NAMESPACE
            value: {{ namespace }}
          - name: SENTRY_DSN
            value: `}}{{ .Values.sentry_dsn | quote }}{{`
          - name: PYTHONWARNINGS
            value: 'ignore:Unverified HTTPS request'
          - name: PGAPPNAME
            value: cinder-volume-vmware-{{ name }}
          volumeMounts:
          - name: etccinder
            mountPath: /etc/cinder
          - name: cinder-etc
            mountPath: /etc/cinder/cinder.conf
            subPath: cinder.conf
            readOnly: true
          - name: cinder-etc
            mountPath: /etc/cinder/policy.json
            subPath: policy.json
            readOnly: true
          - name: cinder-etc
            mountPath: /etc/cinder/rootwrap.conf
            subPath: rootwrap.conf
            readOnly: true
          - name: cinder-etc
            mountPath: /etc/cinder/logging.ini
            subPath: logging.ini
            readOnly: true
          - name: volume-config
            mountPath: /etc/cinder/cinder-volume.conf
            subPath: cinder-volume.conf
            readOnly: true
        volumes:
        - name: etccinder
          emptyDir: {}
        - name: cinder-etc
          configMap:
            name: cinder-etc
        - name: volume-config
          configMap:
            name:  volume-vmware-{{ name }}
`}}
