logLevel: info

# Required:
# keystoneEndpoint:
# region:
# ca:
#   certificate:
#   privateKey:
#
# agentUpdateURL:
# agentEndpointURL:

api:
  replicaCount: 2
  image:
    repository: sapcc/arc
    tag: latest
    pullPolicy: IfNotPresent
  service:
    name: arc
    type: ClusterIP
    externalPort: 80
    internalPort: 80
    externalTLSPort: 443
    internalTLSPort: 443
    # externalIP: 8.8.8.8
  tls:
    enabled: false
  ingress:
    enabled: false
    #tlsCertificate:
    #tlsKey:

updatesProxy:
  replicaCount: 2
  #storageUrl: https://objectstore.example.com/v1/AUTH_asdadadad/
  #ingress:
  #  - tlsCertificate:
  #    privateKey:
  #    hosts: []
  #channels:
  #  - name: stable.arc.example.con
  #    container: arc-releases-stable

