apiVersion: v1
kind: Service

metadata:
  name: {{ include "prometheus.name" . }}
  labels:
    prometheus: {{ include "prometheus.name" . }}

spec:
  selector:
    app: prometheus
    prometheus: {{ include "prometheus.name" . }}
  ports:
    - name: http
      port: 9090
